services:
  app:
    build:
      context: .
      args:
        - NPM_COMMAND=start:dev
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - ORGANISATION_ID=hy
      - LOCALOIDC=false
    env_file: ".env"
    volumes:
      - ./:/opt/app-root/src
    ports:
      - 3000:3000
      - 8000:8000
    container_name: riksutin_dev
    networks:
      - riksutin_internal

  db:
    image: postgres:15.18
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/data
    container_name: riksutin_db
    networks:
      - riksutin_internal

  redis:
    image: redis:7-alpine
    container_name: riksutin_redis
    networks:
      - riksutin_internal

  mock:
    build:
      context:
        data_source_mock 
    container_name: data_source_mock
    env_file: ".env"
    ports:
      - 3001:3000
    networks:
      - riksutin_internal

  # login.toska.localhost:
  #   image: toska-login-local
  #   ports: 
  #     - 3042:3042
  #   volumes:
  #     - ./toska_login/accounts.json:/opt/app-root/src/accounts.json
  #     - ./toska_login/configuration.json:/opt/app-root/src/configuration.json
  #   networks:
  #     - riksutin_internal

volumes:
  pg_data:

networks:
  riksutin_internal:
    driver: bridge