services:
  app:
    build:
      context: .
      args:
        - NPM_COMMAND=start:dev
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - ORGANISATION_ID=hy
    env_file: ".env"
    volumes:
      - ./:/opt/app-root/src
    ports:
      - 3000:3000
      - 8000:8000
    container_name: riksutin_dev

  db:
    image: postgres:15.7
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/data
    container_name: riksutin_db

  redis:
    image: redis:7-alpine
    container_name: riksutin_redis

  mock:
    build:
      context:
        data_source_mock 
    container_name: data_source_mock
    env_file: ".env"
    ports:
      - 3001:3000


volumes:
  pg_data:
